© *Copyright: Este notebook **no** puede ser distribuido parcial o totalmente sin autorización*

# **1. Pandas**
Prof. Rosa Paccotacya Yanque

<img src="https://codigital.ec/wp-content/uploads/2023/02/biblioteca_pandas.jpg" alt="data" width="650">

Pandas es una poderosa biblioteca de Python que facilita el análisis de datos. Es especialmente útil para trabajar con datos almacenados en formatos de tabla como .csv, .tsv o .xlsx. Con Pandas, puede cargar, procesar y analizar datos fácilmente utilizando comandos similares a SQL. Cuando se utiliza junto con Matplotlib y Seaborn, Pandas ofrece una gran cantidad de oportunidades para visualizar y analizar datos tabulares.

Las estructuras de datos principales en Pandas son Series y DataFrames.

- Una **Serie** es una matriz indexada unidimensional de un solo tipo de datos, mientras que un DataFrame es una tabla bidimensional donde cada columna contiene datos del mismo tipo. Piense en un DataFrame como una colección de objetos de serie.

- Los **DataFrames** son ideales para representar datos del mundo real, donde cada fila representa una instancia (como una observación) y cada columna representa una característica de esa instancia.

<img src="https://storage.googleapis.com/lds-media/images/series-and-dataframe.width-1200.png" alt="data" width="650">

## **Características**




* **Manipulación Flexible de Datos**: Pandas proporciona estructuras de datos flexibles y potentes, como DataFrames y Series, que permiten manipular datos de manera fácil y eficiente. Estas estructuras están diseñadas para trabajar con datos tabulares de manera intuitiva, lo que facilita la exploración y el análisis de datos.
* **Funcionalidades Integradas para Análisis de Datos**: Pandas ofrece una amplia gama de funcionalidades integradas para el análisis de datos, incluyendo la limpieza, transformación, agregación y visualización de datos. Esto incluye operaciones como la selección, filtrado, agrupamiento, agregación y fusión de datos, así como la gestión de valores faltantes y duplicados.
* **Integración con Otras Bibliotecas**: Pandas se integra bien con otras bibliotecas populares de Python para análisis de datos y visualización, como NumPy, Matplotlib, SciPy y Scikit-Learn. Esto facilita la combinación de funcionalidades de diferentes bibliotecas para realizar tareas complejas de análisis de datos.
* **Eficiencia en el Tratamiento de Datos Grandes**: Pandas está diseñado para manejar eficientemente conjuntos de datos grandes y complejos. Utiliza operaciones vectorizadas y optimizaciones internas para mejorar el rendimiento y reducir el consumo de memoria, lo que lo hace adecuado para trabajar con datos de tamaño considerable.
* **Flexibilidad en la Entrada y Salida de Datos**: Pandas proporciona herramientas para leer y escribir datos desde y hacia una variedad de formatos, incluyendo archivos CSV, Excel, SQL, HDF5 y JSON. Esto facilita la integración de Pandas en flujos de trabajo de análisis de datos que involucran diferentes fuentes de datos.

In [1]:
import pandas as pd

## **Series**

Una serie es un objeto unidimensional similar a una matriz que contiene una secuencia de valores (de tipos similares a los tipos NumPy) del mismo tipo y una matriz asociada de etiquetas de datos, llamada índice. La Serie más simple se forma a partir de sólo una serie de datos usando `pd.Series()`:

In [2]:
# Creando una serie a partir de una lista. En este caso no se proporcionan los índices (o etiquetas),
# entonces pandas crea los índices automáticamente

lst = ['a','b','c','d','e']
series = pd.Series(lst)
print(series)

0    a
1    b
2    c
3    d
4    e
dtype: object

Como se vió no hemos definido el índice y Pandas asignó como índice una secuencia `range` de números enteros desde el 0 hasta N-1.

Podemos especificar un índice usando un argumento opcional cuando construimos la serie.

In [3]:
fruit_name_list = ['apple', 'banana', 'cherry', 'dates', 'elderberry']
fruit_weight_list = [180, 120, 15, 650, 450]

my_fruit_series = pd.Series(data=fruit_weight_list,
                            index=fruit_name_list)
my_fruit_series

apple         180
banana        120
cherry         15
dates         650
elderberry    450
dtype: int64

In [4]:
# Creando una serie a partir de un diccionario. Las claves del diccionario se convierten en etiquetas y
# los valores de los elementos de la serie

dct = {'A' : 50, 'B' : 10, 'C' : 80, 'D' : 33}
series = pd.Series(dct)
print(series)

A    50
B    10
C    80
D    33
dtype: int64

Para crear copias de un objeto Series se usa el método `.copy()`

In [5]:
series_cp = series.copy()

### Atributos de un serie

- índice
- Valores
- Tipo
- Nombre
- Memoria
-Numero de registros

In [6]:
data ={'Apple': 147000,
'Samsung': 267937,
'Google': 135301,
'Microsoft': 163000,
'Huawei': 197000,
'Dell': 158000,
'Facebook': 58604,
'Foxconn': 878429,
'Sony': 109700}

In [13]:
trabajadores = pd.Series(data, name='Trabajadores en Tech')
print(trabajadores)
print(trabajadores.index, end = '\n--\n')
print(trabajadores.values, end = '\n--\n')
print(trabajadores.dtype, end = '\n--\n')
print(trabajadores.name, end = '\n--\n')
print(trabajadores.nbytes, end = '\n--\n')
print(trabajadores.size, end = '\n--\n')

Apple        147000
Samsung      267937
Google       135301
Microsoft    163000
Huawei       197000
Dell         158000
Facebook      58604
Foxconn      878429
Sony         109700
Name: Trabajadores en Tech, dtype: int64
Index(['Apple', 'Samsung', 'Google', 'Microsoft', 'Huawei', 'Dell', 'Facebook',
       'Foxconn', 'Sony'],
      dtype='object')
--
[147000 267937 135301 163000 197000 158000  58604 878429 109700]
--
int64
--
Trabajadores en Tech
--
72
--
9
--

In [15]:
#Selección  usando indices numericos, similar a lista, tambien se puede usar iloc
trabajadores[0:4:2]

Apple     147000
Google    135301
Name: Trabajadores en Tech, dtype: int64

In [16]:
trabajadores.iloc[0:4:2]

Apple     147000
Google    135301
Name: Trabajadores en Tech, dtype: int64

PRECAUCIÓN: cuando el corte se realiza con etiquetas, se devuelve el último elemento de la subserie

In [10]:
#Selección usando etiquetas
trabajadores['Apple':'Huawei':2]

Apple     147000
Google    135301
Huawei    197000
Name: Trabajadores en Tech, dtype: int64

In [11]:
trabajadores.loc['Apple':'Huawei':2]

Apple     147000
Google    135301
Huawei    197000
Name: Trabajadores en Tech, dtype: int64

### Actualizar Valores

Al igual que una lista, una serie es mutable, por lo que los valores se pueden actualizar mediante la indexación con .loc o iloc.

In [ ]:

fruit_name_list = ['apple', 'banana', 'cherry', 'dates', 'elderberry']
fruit_weight_list = [180, 120, 15, 45, 75]
my_fruit_series = pd.Series(data=fruit_weight_list, index=fruit_name_list)

In [ ]:
# Actualizar un valor basado en la etiqueta
my_fruit_series.loc['cherry'] = 25
my_fruit_series

In [ ]:
# Actualizar un valor basado en la posicion
my_fruit_series.iloc[2] = 225
my_fruit_series

### Actualizar los indices

El objeto de índice de serie no es mutable, por lo que no podemos usar la indexación posicional para actualizar una sola etiqueta dentro del índice. Sin embargo, podemos reasignar una lista de nuevos valores al índice.

In [ ]:
my_fruit_series

In [ ]:
my_fruit_series.index = ['apple', 'grapes', 'cherry', 'dates', 'elderberry']
my_fruit_series

### Operaciones con Series
### Operaciones lógicas
Para usar los operadores booleanos se usa & para and y | para or

In [ ]:
trabajadores

In [ ]:
# Filtrar empresas que tengan más de 200000 trabajadores/as
trabajadores > 200_000

In [ ]:
#Hemos obtenido una serie «booleana».
#Si queremos aplicar esta «máscara», podemos hacerlo con indexado
trabajadores[trabajadores>200000]

*Ejercicio* Encuentra las frutas que pesan menos de 20 gr y más de 100 gr, dada la siguiente serie:



```
fruit_name_list = ['apple', 'banana', 'cherry', 'dates', 'elderberry']
fruit_weight_list = [180, 120, 15, 45, 75]

my_fruit_series = pd.Series(data=fruit_weight_list,
                            index=fruit_name_list)
```

In [ ]:
#tu codigo va aqui

### Ordenación

Ambos métodos admiten el parámetro ascending para indicar si la ordenación es ascendente (True) o descendente (False); y también admiten el parámetro inplace para indicar si se quiere modificar los valores de la serie (True) o devolver una nueva ya ordenada (False).

In [ ]:
#employees.sort_values()

In [ ]:
# employees.sort_index()

### Contar elementos
Si queremos obtener una «tabla de frecuencias» podemos contar los valores que existen en nuestra serie:

In [ ]:
marks = pd.Series([5, 5, 3, 6, 5, 2, 8, 3, 8, 7, 6])

marks.value_counts()

In [ ]:
# Numero de valores unicos
marks.nunique()

In [ ]:
# Numer de valores no nulos
marks.count()

### Operaciones aritméticas y Funciones estadísticas

In [ ]:
marks = marks / 2

In [ ]:
#Ejemplos
serie.mean()

### De Series a otro tipo de dato

In [ ]:
#employees.to_list()

In [ ]:
#employees.to_dict()

In [ ]:
#employees.to_csv()
serie.to_csv('frutas.csv')

In [ ]:
#employees.to_frame()

# Dataframes


Un Dataframe es un objeto de Pandas para organizar datos que actúa de manera muy similar a una hoja de cálculo.  Es bidimensional porque tiene filas y columnas.

Una Serie es una única columna de datos con un índice que identifica filas. Un marco de datos es una colección de series, que puede considerar como columnas, que comparten el mismo índice.

El índice compartido nos permitirá examinar, organizar y manipular muchos datos de manera muy eficiente.

![picture](https://drive.google.com/uc?export=view&id=1Vc-dO62jOh_35LMFpUPUf9MIzJXa7N5c)

Los Dataframes pueden ser creados de muchas maneras diferentes:
- __2-D NumPy array:__ Una matriz de datos, pudiendo pasar los índices de las filas y columnas
- __Dict of arrays, lists, or tuples:__ Cada secuencia se vuelve una columna. Las secuencias deben tener el mismo número de elementos.
- __Dict of Series:__ Cada serie se vuelve una columna. Los índices de cada serie son unidos para formar los índices de cada fila.
- __Dict of dicts:__ Cada diccionario se vuelve una columna. Las claves de los diccionarios se unen para formar los índices de las filas.
- __List of dicts or Series:__ Cada item se vuelve una línea en el DataFrame. La unidad de las claves (para dicionário) o índices (para Series) genera el  índice de las columnas.
- __List of lists or tuples:__  Similar a una matriz de numpy

In [ ]:
import pandas as pd
# Creando un dataframe con un diccionario de listas
d = {'state' : ['FL', 'FL', 'GA', 'GA', 'GA'],
     'year' :  [2010, 2011, 2008, 2010, 2011],
     'pop' :   [18.8, 19.1, 9.7, 9.7, 9.8]}

df_d = pd.DataFrame(d,index=['a','b','c','d','e'])

In [ ]:
df_d

  state  year   pop
a    FL  2010  18.8
b    FL  2011  19.1
c    GA  2008   9.7
d    GA  2010   9.7
e    GA  2011   9.8

In [ ]:
ventas = {"Entradas":[41,32,56,18],
          "Salidas": [27, 54, 6, 78],
          "Cambio":  [3.32, 3.33,3.35,3.4],
          "Descuentos":["si", "No", "No", "Si"]}
print(ventas)

ventas_df = pd.DataFrame(ventas)

{'Entradas': [41, 32, 56, 18], 'Salidas': [27, 54, 6, 78], 'Cambio': [3.32, 3.33, 3.35, 3.4], 'Descuentos': ['si', 'No', 'No', 'Si']}

In [ ]:
ventas_df

   Entradas  Salidas  Cambio Descuentos
0        41       27    3.32         si
1        32       54    3.33         No
2        56        6    3.35         No
3        18       78    3.40         Si

In [ ]:
# Con etiquetas en los indices
ventas_df = pd.DataFrame(ventas, index = ["Ene", "Feb", "Mar", "Abr"])

ventas_df

     Entradas  Salidas  Cambio Descuentos
Ene        41       27    3.32         si
Feb        32       54    3.33         No
Mar        56        6    3.35         No
Abr        18       78    3.40         Si

**OJO:** Dos funciones son muy útiles para analizar rapidamente un dataframe **df.head() y df.dtypes()**

In [ ]:
import numpy as np
entradas = np.random.randint(0,100,100) # lista array numpy
salidas =  np.random.randint(0,100,100) # array numpy
almacen = pd.DataFrame({"entradas": entradas, "salidas_a": salidas})
#almacen.shape
#almacen.head()

In [ ]:
almacen.shape

(100, 2)

In [ ]:
almacen.head()# Primeras N filas del dataframe

   entradas  salidas_a
0        32          7
1        96         45
2        21         99
3        14         12
4        16         80

In [ ]:
almacen['Saldo'] = almacen["entradas"] - almacen["salidas_a"]
almacen.head()

   entradas  salidas_a  Saldo
0        32          7     25
1        96         45     51
2        21         99    -78
3        14         12      2
4        16         80    -64

In [ ]:
df_d.dtypes # Muestra el tipo de dato de cada columna

state     object
year       int64
pop      float64
dtype: object

* De forma similar a  las series, podemos acceder a índices y valores

In [ ]:
ventas_df

     Entradas  Salidas  Cambio Descuentos
Ene        41       27    3.32         si
Feb        32       54    3.33         No
Mar        56        6    3.35         No
Abr        18       78    3.40         Si

In [ ]:
print(ventas_df.values)
print(ventas_df.index)
print(ventas_df.columns)
print(ventas_df.shape)

[[41 27 3.32 'si']
 [32 54 3.33 'No']
 [56 6 3.35 'No']
 [18 78 3.4 'Si']]
Index(['Ene', 'Feb', 'Mar', 'Abr'], dtype='object')
Index(['Entradas', 'Salidas', 'Cambio', 'Descuentos'], dtype='object')
(4, 4)

#### Manipulando y accediendo a las **COLUMNAS**

- Las columnas pueden ser accedidas:
  - usando sus rótulos dentro de []
  - usando sus rótulos como atributo
  - usando lista de rótulos dentro de [] (acceder a  varias columnas)

In [ ]:
df_d

  state  year   pop
a    FL  2010  18.8
b    FL  2011  19.1
c    GA  2008   9.7
d    GA  2010   9.7
e    GA  2011   9.8

In [ ]:
df_d['year']

a    2010
b    2011
c    2008
d    2010
e    2011
Name: year, dtype: int64

In [ ]:
df_d.year

a    2010
b    2011
c    2008
d    2010
e    2011
Name: year, dtype: int64

In [ ]:
print(df_d[['pop','year']])

    pop  year
a  18.8  2010
b  19.1  2011
c   9.7  2008
d   9.7  2010
e   9.8  2011

- Columnas puede ser creadas simplemente creando un nuevo rótulo
- Columnas pueden ser eliminadas usando el método `drop` o `del`

In [ ]:
print(df_d)
# Creando una nueva columna
df_d['new_col'] = np.zeros((df_d.shape[0])) # el comando shape funciona como en numpy
df_d

  state  year   pop
a    FL  2010  18.8
b    FL  2011  19.1
c    GA  2008   9.7
d    GA  2010   9.7
e    GA  2011   9.8

  state  year   pop  new_col
a    FL  2010  18.8      0.0
b    FL  2011  19.1      0.0
c    GA  2008   9.7      0.0
d    GA  2010   9.7      0.0
e    GA  2011   9.8      0.0

In [ ]:
# eliminando la nueva columna
df_d = df_d.drop(['new_col'], axis=1) # O del df_d['new_col']
print(df_d)

  state  year   pop
a    FL  2010  18.8
b    FL  2011  19.1
c    GA  2008   9.7
d    GA  2010   9.7
e    GA  2011   9.8

#### Manipulando y accediendo a las **FILAS**

- Las filas pueden ser accedidas usando:
  - **iloc**: manipula el DataFrame como una matriz con índices enteros, así como Numpy
  - **loc**: Selecciona las filas por los rótulos (índices) o por máscara booleana

In [ ]:
df_d

  state  year   pop
a    FL  2010  18.8
b    FL  2011  19.1
c    GA  2008   9.7
d    GA  2010   9.7
e    GA  2011   9.8

In [ ]:
print(df_d)
print(5*'-')
print(df_d.iloc[2]) # retorna una fila como una serie (el rótulo de la linea se vuelve el rótulo de la columna)
print(5*'-')
print(type(df_d.iloc[2]))
print(5*'-')
print(df_d.iloc[2:4,1:])
print(5*'-')
print(type(df_d.iloc[2:4,1:]))

  state  year   pop
a    FL  2010  18.8
b    FL  2011  19.1
c    GA  2008   9.7
d    GA  2010   9.7
e    GA  2011   9.8
-----
state      GA
year     2008
pop       9.7
Name: c, dtype: object
-----
<class 'pandas.core.series.Series'>
-----
   year  pop
c  2008  9.7
d  2010  9.7
-----
<class 'pandas.core.frame.DataFrame'>

In [ ]:
print(df_dod)
print()
print(df_dod.loc[2008])
print()
print(df_dod.loc[[2010, 2011]])
print()
print(df_dod.loc[df_dod['GA'] == 9.7]) # loc acepta expresiones booleanas

        FL   GA
2010  18.1  9.7
2011  19.1  9.8
2008   NaN  9.7

FL    NaN
GA    9.7
Name: 2008, dtype: float64

        FL   GA
2010  18.1  9.7
2011  19.1  9.8

        FL   GA
2010  18.1  9.7
2008   NaN  9.7

In [ ]:
df_d

  state  year   pop
a    FL  2010  18.8
b    FL  2011  19.1
c    GA  2008   9.7
d    GA  2010   9.7
e    GA  2011   9.8

In [ ]:
# Las expresiones booleanas pueden ser combinadas
# & es el operador lógico AND
# Existe también el operador lógico OR | (barra vertical)
print(df_d.loc[(df_d['state'] == 'GA') & (df_d['year'] >= 2010)])

  state  year  pop
d    GA  2010  9.7
e    GA  2011  9.8

In [ ]:
# retornando una lista tipo 'mascara booleana'
print('cond 1')
print((df_d['state'] == 'GA') & (df_d['year'] >= 2010))

cond 1
a    False
b    False
c    False
d     True
e     True
dtype: bool

In [ ]:


print('\ncond 2')
print(df_d['year'] >= 2010)

print('\nand (&)')
print((df_d['state'] == 'GA') & (df_d['year'] >= 2010))

print('\nor (&)')
print((df_d['state'] == 'GA') | (df_d['year'] >= 2010))

cond 2
a     True
b     True
c    False
d     True
e     True
Name: year, dtype: bool

and (&)
a    False
b    False
c    False
d     True
e     True
dtype: bool

or (&)
a    True
b    True
c    True
d    True
e    True
dtype: bool

In [ ]:
# Otra alternativa es la función query
print(df_d.query("state == 'GA' and year >= 2010"))

  state  year  pop
d    GA  2010  9.7
e    GA  2011  9.8

- Al igual que las series, también es posible ordenar por índice, pero para ordenar por valor es necesario definir la columna.

In [ ]:
df_d

  state  year   pop
a    FL  2010  18.8
b    FL  2011  19.1
c    GA  2008   9.7
d    GA  2010   9.7
e    GA  2011   9.8

In [ ]:
df_d = df_d.sort_values('year')
df_d

  state  year   pop
c    GA  2008   9.7
a    FL  2010  18.8
d    GA  2010   9.7
b    FL  2011  19.1
e    GA  2011   9.8

**OJO:** sort_values, genera una copia. Para modificar el DataFrame, se debe pasar el parámetro `inplace = True` . Tmabien podemos usar df.drop( columns=['']), para eliminar columnas

In [ ]:
print(df_d.sort_values('year'))
print(df_d)
df_d.sort_values('year',inplace=True)
print(df_d)

  state  year   pop
c    GA  2008   9.7
d    GA  2010   9.7
a    FL  2010  18.8
e    GA  2011   9.8
b    FL  2011  19.1
  state  year   pop
c    GA  2008   9.7
d    GA  2010   9.7
e    GA  2011   9.8
a    FL  2010  18.8
b    FL  2011  19.1
  state  year   pop
c    GA  2008   9.7
d    GA  2010   9.7
a    FL  2010  18.8
e    GA  2011   9.8
b    FL  2011  19.1

In [ ]:
df_d.drop(columns=['pop'],inplace=True)

Veamos si se entendió todo

In [ ]:
import pandas as pd
import numpy as np

# crete a sample dataframe
data = pd.DataFrame({
    'age' :     [ 10, 22, 13, 21, 12, 11, 17],
    'section' : [ 'A', 'B', 'C', 'B', 'B', 'A', 'A'],
    'city' :    [ 'Gurgaon', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai'],
    'gender' :  [ 'M', 'F', 'F', 'M', 'M', 'M', 'F'],
    'favourite_color' : [ 'red', np.nan, 'yellow', np.nan, 'black', 'green', 'red']
})
data

   age section     city gender favourite_color
0   10       A  Gurgaon      M             red
1   22       B    Delhi      F             NaN
2   13       C   Mumbai      F          yellow
3   21       B    Delhi      M             NaN
4   12       B   Mumbai      M           black
5   11       A    Delhi      M           green
6   17       A   Mumbai      F             red

Por ejemplo, es posible que necesitemos encontrar todas las filas en nuestro conjunto de datos donde la edad es más de x años, o la ciudad es Delhi, y así sucesivamente.
  -  Ejercicio: Intentemos encontrar las filas donde el valor de la edad es mayor o igual que 15

- Ejercicio: De manera similar, también podemos usar múltiples condiciones para filtrar nuestros datos, como encontrar todas las filas donde la edad es mayor o igual a 12 y el género también es masculino

Por ejemplo, si su conjunto de datos contiene cientos de columnas y queremos ver solo algunas de ellas, podemos agregar una lista de columnas después de la condición dentro de la declaración loc:

  - edad mayor igual a 12 y solo mostrar section y city

In [ ]:
data.loc[(data.age >= 12 ), ['section', 'city']]

  section    city
1       B   Delhi
2       C  Mumbai
3       B   Delhi
4       B  Mumbai
6       A  Mumbai

A menudo tenemos que actualizar los valores de nuestro conjunto de datos en función de una determinada condición. Por ejemplo, si los valores en **edad** son mayores que iguales a 12, entonces queremos actualizar los valores de la sección de la columna para que sean "M".

In [ ]:
data

   age section     city gender favourite_color
0   10       A  Gurgaon      M             red
1   22       B    Delhi      F             NaN
2   13       C   Mumbai      F          yellow
3   21       B    Delhi      M             NaN
4   12       B   Mumbai      M           black
5   11       A    Delhi      M           green
6   17       A   Mumbai      F             red

In [ ]:
data.loc[(data.age >=12 ),['section']]

  section
1       B
2       C
3       B
4       B
6       A

In [ ]:
data.loc[(data.age >=12 ),['section']] = 'M'

In [ ]:
data

   age section     city gender favourite_color
0   10       A  Gurgaon      M             red
1   22       M    Delhi      F             NaN
2   13       M   Mumbai      F          yellow
3   21       M    Delhi      M             NaN
4   12       M   Mumbai      M           black
5   11       A    Delhi      M           green
6   17       M   Mumbai      F             red

si el valor en la edad de la columna es **mayor que 20**, entonces la función **loc** actualizará los valores en la sección de la columna con **"S"** y los valores en la ciudad de la columna con **Pune**:

In [ ]:
data.loc[(data.age >=20),['section','city']]

  section   city
1       M  Delhi
3       M  Delhi

In [ ]:
data.loc[(data.age >=20),['section','city']] =['S','Pune']

In [ ]:
data

   age section     city gender favourite_color
0   10       A  Gurgaon      M             red
1   22       S     Pune      F             NaN
2   13       M   Mumbai      F          yellow
3   21       S     Pune      M             NaN
4   12       M   Mumbai      M           black
5   11       A    Delhi      M           green
6   17       M   Mumbai      F             red

- Ejercicio: Cuantas personas hay por seccion?

- Ejercicio Que ciudades hay en todo el conjunto de datos? Mostrar sin repetir


##Agrupación
El método groupby  permite agrupar filas de datos y llamar a funciones agregadas.

![groupby.png]()

In [ ]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB','GOOG','MSFT','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah','John','Randy','David'],
       'Sales':[200,120,340,124,243,350,275,400,180]}
df = pd.DataFrame(data)
df

In [ ]:
#Por ejemplo, vamos a agrupar los datos a partir de la Compañía
grupo_compania =df.groupby("Company")
grupo_compania

In [ ]:
#Obtengamos las media de la columnas numericas numeric_only =True
print(df.groupby("Company").sum(numeric_only =True))
df.groupby("Company").mean(numeric_only =True)

In [ ]:
#podemos describir el comportamiento estadistico de los grupos obtenidos
grupo_compania.describe()

##Concatenacion de Dataframes
**Concatenación de filas**. Las filas de los DataFrames se concatenan unas a continuación de las otras para formar el nuevo DataFrame. Para ello es necesario que los DataFrames que se combinen tengan el mismo índice de columnas.

![pandas-concatenacion-filas.png]()

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"Nombre":["Carmen", "Luis"], "Sexo":["Mujer", "Hombre"], "Edad":[22, 18]}).set_index("Nombre")
df2 = pd.DataFrame({"Nombre":["María", "Pedro"], "Sexo":["Mujer", "Hombre"], "Edad":[25, 30]}).set_index("Nombre")
df = pd.concat([df1, df2])
df

**Concatenación por columnas** Las columnas de los DataFrames se concatenan unas a continuación de las otras para formar el nuevo DataFrame. Para ello es necesario que los DataFrames que se combinen tengan el mismo índice de filas.
![pandas-concatenacion-columnas.png]()

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"Nombre":["Carmen", "Luis"], "Sexo":["Mujer", "Hombre"]}).set_index("Nombre")
df2 = pd.DataFrame({"Nombre":["Carmen", "Luis", "María"], "Edad":[22, 18, 25]}).set_index("Nombre")
df = pd.concat([df1, df2], axis = 1)
df

## Trabajando con datos temporales

A menudo una columna contiene cadenas que representan fechas. Para convertir estas cadenas al tipo datetime se utiliza el siguiente método:

`to_datetime(columna, formato)`

In [ ]:
df = pd.DataFrame({'Name': ['María', 'Carlos', 'Carmen'], 'Nacimiento':['05-03-2000', '20-05-2001', '10-12-1999']})
print(pd.to_datetime(df.Nacimiento, format = '%d-%m-%Y'))

In [ ]:
df.info()

In [ ]:
df['Nacimiento'].dt.year

# **2. Limpieza, preprocesamiento y manipulación de datos utilizando Pandas**

![](https://i.imgur.com/zfxLzEv.png)

## Lectura de CSV usando Pandas

[Pandas](https://pandas.pydata.org/) es una biblioteca de Python popular que se utiliza para trabajar con datos tabulares (similar a los datos almacenados en una hoja de cálculo). Pandas proporciona funciones de ayuda para leer datos de varios formatos de archivo como CSV, hojas de cálculo de Excel, tablas HTML, JSON, SQL y más.

Usaremos el [Dataset de notificación de casos de dengue al sistema de vigilancia en salud pública del Perú](https://www.datosabiertos.gob.pe/dataset/vigilancia-epidemiol%C3%B3gica-de-dengue) de la Plataforma Nacional de Datos Abiertos.

El archivo contiene datos de pacientes de Dengue en nuestro país en el siguiente formato:

```
departamento,provincia,distrito,localidad,enfermedad,ano,semana,diagnostic,diresa,ubigeo,localcod,edad,tipo_edad,sexo,Unnamed: 14,Unnamed: 15
CUSCO,LA CONVENCION,SANTA ANA,QUILLABAMBA,DENGUE SIN SEÑALES DE ALARMA,2022,1,A97.0,8.0,80901,809010001,39,A,F,,
ANCASH,CASMA,CASMA,CASMA,DENGUE SIN SEÑALES DE ALARMA,2022,1,A97.0,2.0,20801,208010001,13,A,F,,
PIURA,MORROPON,MORROPON,MORROPON,DENGUE SIN SEÑALES DE ALARMA,2022,1,A97.0,32.0,200405,2004050001,15,A,M,,
CAJAMARCA,JAEN,BELLAVISTA,BELLAVISTA,DENGUE SIN SEÑALES DE ALARMA,2022,1,A97.0,38.0,60802,608020001,29,A,F,,
HUANUCO,LEONCIO PRADO,RUPA-RUPA,SUPTE SAN JORGE,DENGUE SIN SEÑALES DE ALARMA,2022,1,A97.0,10.0,100601,1006010032,17,A,F,,
CUSCO,LA CONVENCION,SANTA ANA,QUILLABAMBA,DENGUE SIN SEÑALES DE ALARMA,2022,1,A97.0,8.0,80901,809010001,31,A,M,,
CAJAMARCA,JAEN,JAEN,MAGLLANAL,DENGUE SIN SEÑALES DE ALARMA,2022,1,A97.0,38.0,60801,608010109,51,A,F,,
...
```

Este formato de almacenamiento de datos se conoce como *valores separados por comas* o CSV.

> **CSVs**: un archivo de valores separados por comas (CSV) es un archivo de texto delimitado que usa una coma para separar los valores. Cada línea del archivo es un registro de datos. Cada registro consta de uno o más campos, separados por comas. Un archivo CSV normalmente almacena datos tabulares (números y texto) en texto sin formato, en cuyo caso cada línea tendrá el mismo número de campos.

In [17]:
# Iniciamos siempre importando las librerias
import pandas as pd
import numpy as np

In [18]:
data_df = pd.read_csv('https://raw.githubusercontent.com/RosePY/datasets/refs/heads/main/dengue_2022.csv')

Los datos del archivo se leen y almacenan en un objeto `DataFrame`, una de las estructuras de datos centrales en Pandas para almacenar y trabajar con datos tabulares. Normalmente usamos el sufijo `_df` en los nombres de las variables para los marcos de datos o dataframes.

In [ ]:
data_df.tail()


Podemos ver información básica sobre el marco de datos o *dataframe* usando el método `.info`.

In [ ]:
data_df.info()

Parece que cada columna contiene valores de un tipo de datos específico. Puede ver información estadística para columnas numéricas (media, desviación estándar, valores mínimo / máximo y el número de valores no vacíos) utilizando el método `.describe`.

In [ ]:
data_df.describe()

La propiedad `.columns` contiene la lista de columnas dentro del dataframe.

In [ ]:
data_df.columns

También puede recuperar el número de filas y columnas en el marco de datos usando el método `.shape`.

In [ ]:
data_df.shape

Aquí hay un resumen de las funciones y métodos:

* `pd.read_csv` - Leer datos de un archivo CSV en un objeto` DataFrame` de Pandas
* `.info ()` - Ver información básica sobre filas, columnas y tipos de datos
* `.describe ()` - Ver información estadística sobre columnas numéricas
* `.columns` - Obtiene la lista de nombres de columnas
* `.shape` - Obtiene el número de filas y columnas como una tupla

## Recuperando datos de un dataframe

Recordemos que un dataframe es análogo a un diccionario de listas, por lo que podemos obtener una lista de valores de una columna específica usando la notación de indexación `[]`.

In [ ]:
data_df['edad']

Cada columna se representa mediante la estructura de datos "Serie" (visto en la clase pasada), que es esencialmente una matriz numerosa con algunos métodos y propiedades adicionales.

En lugar de usar la notación de indexación `[]`, Pandas también permite acceder a las columnas como propiedades del dataframe usando la notación `.`.
**Sin embargo, este método solo funciona para columnas cuyos nombres no contienen espacios ni caracteres especiales.**

In [ ]:
data_df.info()

In [ ]:
data_df['Unnamed: 14']

Además, también puede pasar una lista de columnas dentro de la notación de indexación `[]` para acceder a un subconjunto del marco de datos con solo las columnas dadas.

In [ ]:
casos_df = data_df[['departamento', 'edad', 'tipo_edad']]
casos_df

      departamento  edad tipo_edad
0            CUSCO    39         A
1           ANCASH    13         A
2            PIURA    15         A
3        CAJAMARCA    29         A
4          HUANUCO    17         A
...            ...   ...       ...
63220   SAN MARTIN    17         A
63221        PIURA    48         A
63222        PIURA    24         A
63223       LORETO    26         A
63224   SAN MARTIN    25         A

[63225 rows x 3 columns]

**IMPORTANTE** El nuevo data frame `casos_df` es simplemente una "view" del dataframe original` data_df`. Ambos apuntan a los mismos datos en la memoria de la computadora. Cambiar cualquier valor dentro de uno de ellos también cambiará los valores respectivos en el otro. Compartir datos entre dataframes  hace que la manipulación de datos en Pandas sea increíblemente rápida. No necesita preocuparse por la sobrecarga de copiar miles o millones de filas cada vez que desee crear un nuevo dataframe operando en uno existente.

A veces, es posible que necesite una copia completa del dataframe, en cuyo caso puede utilizar el método `copy`.

In [ ]:
data_df_copy = data_df.copy()

In [ ]:
data_df_copy

Los datos dentro de `data_df_copy` están completamente separados de ` data_df`, y cambiar los valores dentro de uno de ellos no afectará al otro.

Para acceder a una fila específica de datos, Pandas proporciona el método `.loc`.

In [ ]:
data_df.loc[15]

En el conjunto de datos existen valores faltantes "NaN".

Podemos encontrar el primer índice que no contiene un valor `NaN` usando el método` first_valid_index` de una columna.

In [ ]:
data_df.isnull().sum()

departamento        0
provincia           0
distrito            0
localidad        4644
enfermedad          0
ano                 0
semana              0
diagnostic          0
diresa             18
ubigeo              0
localcod         2452
edad                0
tipo_edad           0
sexo                0
Unnamed: 14     63225
Unnamed: 15     63225
dtype: int64

Veamos algunas filas antes y después de este índice para verificar que los valores cambian de "NaN" a números reales. Podemos hacer esto pasando un rango a "loc".

In [ ]:
data_df.loc[108:113]

Podemos usar el método `.sample` para recuperar una muestra aleatoria de filas del marco de datos.

In [ ]:
data_df.sample(8)

Tenga en cuenta que, aunque hemos tomado una muestra aleatoria, se conserva el índice original de cada fila; esta es una propiedad útil de los marcos de datos.

En esta parte del repaso vimos:

- `data_df ['edad']` - Recuperando columnas como una `Serie` usando el nombre de la columna
- `localidad[243]` - Recuperando valores de una `Serie` usando un índice
- `data_df.at[243, 'edad']` - Recuperando un solo valor de un dataframe
- `data_df.copy ()` - Creando una copia profunda de un marco de datos
- `data_df.loc[243]` - Recuperando una fila o rango de filas de datos del dataframe
- `head`,` tail` y `sample` - Recuperar múltiples filas de datos del dataframe
- `data_df.localidad.first_valid_index` - Encontrar el primer índice no vacío de una serie

## Limpieza de Datos

 La naturaleza de los datos del mundo real incluye datos erroneos. Podría ser un error de entrada de datos, o el gobierno puede haber emitido una corrección para tener en cuenta los errores de conteo en el pasado.

In [ ]:
data_df.info()

Por ahora, supongamos que se trata de un error de entrada de datos. Podemos utilizar uno de los siguientes enfoques para tratar el valor faltante o defectuoso:
1. Reemplazar con "0".
2. Reemplazar con el promedio de toda la columna.
3. Reemplazar con el promedio de los valores de la fecha anterior y siguiente.
4. Descartar la fila por completo

El enfoque que elija requiere algo de contexto sobre los datos y el problema.

In [ ]:
data_df.drop(['localidad', 'localcod', 'Unnamed: 14', 'Unnamed: 15'], axis = 1, inplace = True)

In [ ]:
data_df.info()

In [ ]:
data_df.dropna(axis=0, inplace = True) # Eliminando filas con valores faltante

In [ ]:
data_df.info()

In [ ]:
data_df.describe()

           ano        semana        diresa         ubigeo          edad
count  63207.0  63207.000000  63207.000000   63207.000000  63207.000000
mean    2022.0     21.707786     21.838531  146718.016675     29.876754
std        0.0     14.160134     11.726612   67958.961466    140.768054
min     2022.0      1.000000      2.000000   10101.000000      1.000000
25%     2022.0     12.000000     12.000000  110101.000000     14.000000
50%     2022.0     18.000000     17.000000  160201.000000     26.000000
75%     2022.0     30.000000     32.000000  200401.000000     41.000000
max     2022.0     52.000000     99.000000  999999.000000  35109.000000

In [ ]:
data_df.index[data_df['edad'] == 35109]

In [ ]:
data_df.loc[26259]

In [ ]:
data_df.drop(26259,inplace = True)

In [ ]:
data_df.describe()

In [ ]:
data_df.loc[data_df['edad'] == 106]

In [ ]:
data_df.departamento.unique()

In [ ]:
data_df.loc[data_df['departamento'] == '\\N']

In [ ]:
data_df.loc[data_df['departamento'] == '\\N'].index

In [ ]:
data_df.drop(data_df.loc[data_df['departamento'] == '\\N'].index, inplace = True)

In [ ]:
data_df.departamento.unique()

In [ ]:
data_df.shape

In [ ]:
data_df.provincia.unique()

In [ ]:
data_df.distrito.unique()

In [ ]:
data_df.diagnostic.unique()

In [ ]:
data_df.sexo.unique()

In [ ]:
df_clean = data_df.copy()

## Analizando datos en dataframes

Vamos a responder algunas preguntas de nuestros datos

In [ ]:
data_df.head(3)

,departamento,provincia,distrito,enfermedad,ano,semana,diagnostic,diresa,ubigeo,edad,tipo_edad,sexo
0,CUSCO,LA CONVENCION,SANTA ANA,DENGUE SIN SEÑALES DE ALARMA,2022,1,A97.0,8.0,80901,39,A,F
1,ANCASH,CASMA,CASMA,DENGUE SIN SEÑALES DE ALARMA,2022,1,A97.0,2.0,20801,13,A,F
2,PIURA,MORROPON,MORROPON,DENGUE SIN SEÑALES DE ALARMA,2022,1,A97.0,32.0,200405,15,A,M

In [ ]:
#Cantidad de casos por departamento

departamento
PIURA            12150
LORETO            8926
ICA               5084
UCAYALI           4824
SAN MARTIN        4270
JUNIN             4157
CUSCO             3686
MADRE DE DIOS     3641
CAJAMARCA         3638
AMAZONAS          3575
LAMBAYEQUE        2386
ANCASH            2145
HUANUCO           1580
LIMA               938
AYACUCHO           782
TUMBES             723
PASCO              496
LA LIBERTAD        162
PUNO                25
CALLAO               8
Name: count, dtype: int64

In [ ]:
#Mujeres y varones con dengue

sexo
F    33811
M    29385
Name: count, dtype: int64

In [ ]:
# Cantidad de casos por enfermedad

enfermedad
DENGUE SIN SEÑALES DE ALARMA    55279
DENGUE CON SEÑALES DE ALARMA     7705
DENGUE GRAVE                      212
Name: count, dtype: int64

También podemos formular consultas más complejas que involucran múltiples columnas.

In [ ]:
# Cantidad de casos por provincia en un departamento especifico

provincia
CALCA              16
LA CONVENCION    3627
PAUCARTAMBO         3
QUISPICANCHI       40
dtype: int64

In [ ]:
# Cantidad de casos por provincia y por tipo de enfermedad

provincia  enfermedad
CASMA      DENGUE CON SEÑALES DE ALARMA     152
           DENGUE GRAVE                      11
           DENGUE SIN SEÑALES DE ALARMA    1933
HUARMEY    DENGUE CON SEÑALES DE ALARMA       1
           DENGUE SIN SEÑALES DE ALARMA      16
SANTA      DENGUE SIN SEÑALES DE ALARMA      32
dtype: int64

In [ ]:
#Crear funcion casos_enfermedad(departamento)

In [ ]:
casos_enfermedad('UCAYALI')

provincia         enfermedad
ATALAYA           DENGUE CON SEÑALES DE ALARMA      96
                  DENGUE GRAVE                       2
                  DENGUE SIN SEÑALES DE ALARMA     611
CORONEL PORTILLO  DENGUE CON SEÑALES DE ALARMA     512
                  DENGUE GRAVE                      23
                  DENGUE SIN SEÑALES DE ALARMA    3077
PADRE ABAD        DENGUE CON SEÑALES DE ALARMA      83
                  DENGUE GRAVE                       2
                  DENGUE SIN SEÑALES DE ALARMA     416
PURUS             DENGUE CON SEÑALES DE ALARMA       1
                  DENGUE SIN SEÑALES DE ALARMA       1
dtype: int64

In [ ]:
# CANTIDAD DE CASOS EN NIÑOS MENORES A 5 AÑOS POR DEPARTAMENTO

departamento
AMAZONAS         168
ANCASH            47
AYACUCHO          24
CAJAMARCA        107
CUSCO             57
HUANUCO           65
ICA              117
JUNIN            122
LA LIBERTAD        4
LAMBAYEQUE        38
LIMA              22
LORETO           654
MADRE DE DIOS    148
PASCO             27
PIURA            451
SAN MARTIN       147
TUMBES            22
UCAYALI          267
dtype: int64

Podemos adicionar esa serie como una nueva columna del dataframe

In [ ]:
df_clean['caso_severo'] = df_clean.edad >= 60

In [ ]:
df_clean.head(8)

In [ ]:
df_clean.groupby(df_clean.departamento).size().sort_values(ascending = False)

In [ ]:
df_clean.departamento.value_counts()


## Escritura de datos en archivos

Después de completar su análisis y agregar nuevas columnas, debe volver a escribir los resultados en un archivo. De lo contrario, los datos se perderán cuando se  cierre el colab.

In [ ]:
columnas_que_quiero = ['departamento', 'enfermedad','caso_severo']
resultado_df = df_clean[ columnas_que_quiero]

In [ ]:
resultado_df

      departamento                    enfermedad  caso_severo
0            CUSCO  DENGUE SIN SEÑALES DE ALARMA        False
1           ANCASH  DENGUE SIN SEÑALES DE ALARMA        False
2            PIURA  DENGUE SIN SEÑALES DE ALARMA        False
3        CAJAMARCA  DENGUE SIN SEÑALES DE ALARMA        False
4          HUANUCO  DENGUE SIN SEÑALES DE ALARMA        False
...            ...                           ...          ...
63220   SAN MARTIN  DENGUE SIN SEÑALES DE ALARMA        False
63221        PIURA  DENGUE SIN SEÑALES DE ALARMA        False
63222        PIURA  DENGUE SIN SEÑALES DE ALARMA        False
63223       LORETO  DENGUE SIN SEÑALES DE ALARMA        False
63224   SAN MARTIN  DENGUE SIN SEÑALES DE ALARMA        False

[63196 rows x 3 columns]

Para escribir el dataframe de datos en un archivo, podemos usar la función `to_csv`.

In [ ]:
df_clean.to_csv('dengue_clean.csv', index=None)

In [ ]:
resultado_df.to_csv('resultado.csv', index=None)


La función `to_csv` también incluye una columna adicional para almacenar el índice del dataframe por defecto. Pasamos `index = None` para desactivar este comportamiento

# **3. Visualizaciones**

In [ ]:
data_df.semana.value_counts().sort_index()

In [ ]:
data_df.semana.value_counts().sort_index().plot()
plt.title('Cantidad de casos de dengue por semana')
plt.ylabel('Cantidad de casos')
plt.show()

In [ ]:
import matplotlib.pyplot as plt

data_df.groupby('enfermedad').size().plot(kind = 'bar')
plt.title('Cantidad de casos por enfermedad')
plt.ylabel('Cantidad de casos')
plt.show()

Más recursos sobre visualización lo pueden ver aqui:
- https://joserzapata.github.io/courses/python-ciencia-datos/visualizacion/plotly/
- Slides Google Classroom

# Referencias

* [The Python and Pandas Field Guide](https://snakebear.science/index.html): An Introduction to Computer and Data Science



* Aprende Python - Ciencia de Datos
https://aprendepython.es/pypi/datascience/